'use client';
import {useEffect,useRef,useState} from 'react';
import {supabase} from '../../lib/supabase';
type Vehicle='okada'|'keke';
const nextStatus:{[k:string]:string}={driver_assigned:'driver_arriving',driver_arriving:'driver_waiting',driver_waiting:'in_progress'};
export default function Driver(){
 const [session,setSession]=useState<any>(null),[vehicle,setVehicle]=useState<Vehicle>('okada'),[online,setOnline]=useState(false),[msg,setMsg]=useState('Offline'),[offers,setOffers]=useState<any[]>([]),[ride,setRide]=useState<any>(null),[fare,setFare]=useState('');
 const watchId=useRef<number|null>(null),rideId=useRef<string|null>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));return()=>{if(watchId.current!==null)navigator.geolocation.clearWatch(watchId.current)}},[]);
 async function sendLocation(p:GeolocationPosition){const c=p.coords;if(rideId.current)await supabase.rpc('record_ride_driver_location',{p_ride_id:rideId.current,p_lat:c.latitude,p_long:c.longitude,p_accuracy_meters:c.accuracy,p_heading:c.heading,p_speed_mps:c.speed});else if(online)await supabase.rpc('update_driver_live_location',{p_lat:c.latitude,p_long:c.longitude,p_accuracy_meters:c.accuracy,p_heading:c.heading,p_speed_mps:c.speed});}
 async function toggleOnline(){if(!session)return setMsg('Sign in first.');if(!online){if(!navigator.geolocation)return setMsg('GPS unavailable');setMsg('Starting Kaduna GPS…');const {error}=await supabase.from('drivers').update({is_online:true}).eq('id',session.user.id);if(error)return setMsg(error.message);setOnline(true);setMsg('Online — waiting for Kaduna rides.');watchId.current=navigator.geolocation.watchPosition(sendLocation,e=>setMsg(e.message),{enableHighAccuracy:true,maximumAge:3000,timeout:15000});}else{if(watchId.current!==null)navigator.geolocation.clearWatch(watchId.current);watchId.current=null;await supabase.from('drivers').update({is_online:false}).eq('id',session.user.id);setOnline(false);setMsg('Offline');}}
 useEffect(()=>{if(!session||!online)return;const ch=supabase.channel('offers-'+session.user.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'ride_offers',filter:'driver_id=eq.'+session.user.id},({new:o})=>setOffers(x=>[o,...x])).subscribe();return()=>{supabase.removeChannel(ch)}},[session,online]);
 async function accept(o:any){setMsg('Accepting…');const {data:v}=await supabase.from('vehicles').select('id').eq('driver_id',session.user.id).eq('type',vehicle).eq('is_active',true).limit(1);if(!v?.[0])return setMsg('No active vehicle registered.');const {data,error}=await supabase.rpc('accept_ride',{p_ride_id:o.ride_id,p_driver_id:session.user.id,p_vehicle_id:v[0].id});if(error)return setMsg(error.message);setRide(data);rideId.current=data.id;setOffers([]);setMsg('Ride accepted. Navigate to pickup.');}
 async function advance(){if(!ride)return;const s=nextStatus[ride.status];if(!s)return;setMsg('Updating trip…');const {data,error}=await supabase.rpc('update_ride_status',{p_ride_id:ride.id,p_status:s});if(error)return setMsg(error.message);setRide(data);setMsg(s==='driver_arriving'?'Heading to pickup':s==='driver_waiting'?'Arrived at pickup':'Trip started — passenger is onboard.');}
 async function complete(){if(!ride)return;const n=Number(fare);if(!n||n<=0)return setMsg('Enter final fare.');const {data,error}=await supabase.rpc('complete_ride_and_record_earnings',{p_ride_id:ride.id,p_driver_id:session.user.id,p_final_fare:n});if(error)return setMsg(error.message);setRide(data);rideId.current=null;setFare('');setMsg('Trip completed. Earnings recorded.');}
 useEffect(()=>{if(!ride?.id)return;const ch=supabase.channel('ride-'+ride.id).on('postgres_changes',{event:'UPDATE',schema:'public',table:'rides',filter:'id=eq.'+ride.id},({new:r})=>setRide(r)).subscribe();return()=>{supabase.removeChannel(ch)}},[ride?.id]);
 if(!session)return <main style={{maxWidth:600,margin:'70px auto',padding:24}}><div className="panel"><h1>GoKeke Driver</h1><p>Please sign in.</p></div></main>;
 const action=ride?nextStatus[ride.status]:null;
 return <main style={{maxWidth:850,margin:'30px auto',padding:24}}><h1>GoKeke Driver — Kaduna</h1><p>{online?'🟢 Online — GPS active':'⚪ Offline'}</p><div style={{display:'flex',gap:10}}><button className={'btn '+(vehicle==='okada'?'lime':'dark')} onClick={()=>setVehicle('okada')}>Okada</button><button className={'btn '+(vehicle==='keke'?'lime':'dark')} onClick={()=>setVehicle('keke')}>Keke</button><button className="btn lime" onClick={toggleOnline}>{online?'Go offline':'Go online'}</button></div><p>{msg}</p>{offers.map(o=><div className="panel" key={o.id} style={{marginTop:12}}><h3>New nearby {vehicle} request</h3><p>{Math.round(Number(o.distance_meters||0))} m from pickup</p><button className="btn lime" onClick={()=>accept(o)}>Accept</button></div>)}{ride&&<div className="panel" style={{marginTop:20}}><h2>Active trip</h2><p><b>Status:</b> {ride.status}</p><p><b>Pickup:</b> {ride.pickup_address}</p><p><b>Destination:</b> {ride.destination_address}</p>{action&&<button className="btn lime" onClick={advance}>{action==='driver_arriving'?'Start navigation to pickup':action==='driver_waiting'?'I have arrived':'Start trip'}</button>}{ride.status==='in_progress'&&<div style={{marginTop:16}}><input value={fare} onChange={e=>setFare(e.target.value)} type="number" placeholder="Final fare (NGN)" style={{padding:12,width:'100%'}}/><button className="btn lime" style={{marginTop:10}} onClick={complete}>Complete trip</button></div>}{ride.status==='completed'&&<p>✓ Trip completed and driver earnings recorded.</p>}</div>}</main>;
}