'use client';import{useEffect,useState}from'react';import{supabase}from'../lib/supabase';
function b64ToUint8Array(base64:string){const padding='='.repeat((4-base64.length%4)%4);const raw=atob((base64+padding).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
export default function Notifications(){const[items,setItems]=useState<any[]>([]),[open,setOpen]=useState(false),[push,setPush]=useState(false),[pushMsg,setPushMsg]=useState('');
useEffect(()=>{let active=true;let ch:any;(async()=>{const{data:u}=await supabase.auth.getUser();if(!u.user)return;const{data}=await supabase.from('notifications').select('*').order('created_at',{ascending:false}).limit(30);if(active&&data)setItems(data);if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('/sw.js')}catch{}if('PushManager'in window){try{const reg=await navigator.serviceWorker.ready;setPush(!!await reg.pushManager.getSubscription())}catch{}}
ch=supabase.channel('notifications-'+u.user.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:'user_id=eq.'+u.user.id},({new:n})=>{setItems(x=>[n,...x].slice(0,30));if('Notification'in window&&Notification.permission==='granted')new Notification(n.title,{body:n.body})}).subscribe();})();return()=>{active=false;if(ch)supabase.removeChannel(ch)}},[]);
const unread=items.filter(x=>!x.read_at).length;
async function enablePush(){setPushMsg('');const key=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(!key){setPushMsg('Push is ready for configuration. Add NEXT_PUBLIC_VAPID_PUBLIC_KEY to enable background push.');return}try{if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('Push notifications are not supported in this browser.');if(await Notification.requestPermission()!=='granted')throw new Error('Notification permission was not granted.');const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64ToUint8Array(key)});const j=sub.toJSON();const{data:u}=await supabase.auth.getUser();if(!u.user||!j.endpoint||!j.keys?.p256dh||!j.keys?.auth)throw new Error('Could not create a push subscription.');const{error}=await supabase.from('push_subscriptions').upsert({user_id:u.user.id,endpoint:j.endpoint,p256dh:j.keys.p256dh,auth:j.keys.auth,user_agent:navigator.userAgent,updated_at:new Date().toISOString()},{onConflict:'user_id,endpoint'});if(error)throw error;setPush(true);setPushMsg('Push notifications enabled.')}catch(e:any){setPushMsg(e?.message||'Could not enable push notifications.')}}
async function read(id:string){const now=new Date().toISOString();await supabase.from('notifications').update({read_at:now}).eq('id',id);setItems(x=>x.map(n=>n.id===id?{...n,read_at:now}:n))}
async function all(){const{data:u}=await supabase.auth.getUser();const now=new Date().toISOString();if(u.user)await supabase.from('notifications').update({read_at:now}).eq('user_id',u.user.id).is('read_at',null);setItems(x=>x.map(n=>({...n,read_at:now})))}
return <div style={{position:'fixed',right:20,top:20,zIndex:1000}}><button onClick={()=>setOpen(!open)} style={{border:0,borderRadius:999,padding:'10px 14px',cursor:'pointer'}}>🔔 {unread>0&&<b>{unread}</b>}</button>{open&&<div style={{width:340,maxHeight:560,overflow:'auto',background:'#fff',border:'1px solid #ddd',borderRadius:14,boxShadow:'0 8px 30px #0002',padding:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8}}><b>Notifications</b><button onClick={all}>Mark all read</button></div><div style={{marginTop:10}}><button onClick={enablePush} disabled={push} style={{padding:'8px 10px',borderRadius:8,border:'1px solid #ddd',cursor:push?'default':'pointer'}}>{push?'✓ Push enabled':'Enable push notifications'}</button>{pushMsg&&<small style={{display:'block',marginTop:6}}>{pushMsg}</small>}</div>{items.length===0?<p>No notifications yet.</p>:items.map(n=><button key={n.id} onClick={()=>read(n.id)} style={{display:'block',width:'100%',textAlign:'left',border:0,borderBottom:'1px solid #eee',background:n.read_at?'#fff':'#f2f8ff',padding:12,cursor:'pointer'}}><b>{n.title}</b><div>{n.body}</div><small>{new Date(n.created_at).toLocaleString()}</small></button>)}</div>}</div>}